Binary verification

diff --git a/.github/workflows/ci_suite.yml b/.github/workflows/ci_suite.yml
--- a/.github/workflows/ci_suite.yml
+++ b/.github/workflows/ci_suite.yml
@@ -103,17 +103,34 @@ jobs:
 
   compile_llcm:
     if: ( !contains(github.event.head_commit.message, '[ci skip]') )
-    name: Compile LLCM
-    runs-on: windows-latest
-    timeout-minutes: 30
     steps:
-      - uses: actions/checkout@v6
-      - name: Setup Rust Toolchain
-        uses: ./.github/actions/setup_rust
-      - name: Compile LLCM
-        run: |
-          cd llcm
-          cargo build --target ${{env.RUST_REQUIRED_TARGET}}
+    - name: Compile LLCM
+      runs-on: windows-latest
+      timeout-minutes: 30
+      steps:
+        - uses: actions/checkout@v6
+        - name: Setup Rust Toolchain
+          uses: ./.github/actions/setup_rust
+        - name: Compile LLCM
+          run: |
+            cd llcm
+            cargo build --release --target ${{env.RUST_REQUIRED_TARGET}}
+    - name: Verify completed LLCM
+      shell: bash
+      run: |
+        NEW_FILE = "llcm/target/${{ env.RUST_REQUIRED_TARGET }}/debug/llcm.dll"
+        EXISTING_FILE = "llcm.dll"
+
+        NEW_HASH=$(sha256sum "$NEW_FILE" | cut -d ' ' -f1)
+        EXISTING_HASH=$(sha256sum "$EXISTING_FILE" | cut -d ' ' -f1)
+
+        if [ "$NEW_HASH" != "$EXISTING_HASH" ]; then
+          echo "ERROR: Compiled LLCM does not match the existing binary."
+          exit 1
+        fi
+
+        echo "Compiled LLCM matches the existing binary."
+
 
   run_llcm_tests:
     name: Run LLCM Tests
