Fix

diff --git a/.github/workflows/run_unit_tests.yml b/.github/workflows/run_unit_tests.yml
--- a/.github/workflows/run_unit_tests.yml
+++ b/.github/workflows/run_unit_tests.yml
@@ -25,12 +25,29 @@ jobs:
       - name: Download and unzip BYOND
         if: steps.cache.outputs.cache-hit != 'true'
         run: |
-          echo "Download and unzip BYOND $BYOND_MAJOR.$BYOND_MINOR"
-          mkdir -p "$HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}"
-          cd $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
-          curl -L "https://web.archive.org/web/20250322230727/https://www.byond.com/download/build/${BYOND_MAJOR}/${BYOND_MAJOR}.${BYOND_MINOR}_byond_linux.zip" -o byond.zip -A "CMSS13/1.0 Continuous Integration"
-          unzip -o byond.zip
+          max_attempts=3
+          attempt=1
+          minor=$BYOND_MINOR
+          while (( attempt <= max_attempts )); do
+            echo "Download and unzip BYOND $BYOND_MAJOR.$minor"
+            mkdir -p "$HOME/BYOND-${BYOND_MAJOR}.${minor}"
+            cd $HOME/BYOND-${BYOND_MAJOR}.${minor}
+            curl -L "https://web.archive.org/web/20250322230727/https://www.byond.com/download/build/${BYOND_MAJOR}/${BYOND_MAJOR}.${minor}_byond_linux.zip" -o byond.zip -A "CMSS13/1.0 Continuous Integration"
+            if [[ $? -ne 0 || ! -s byond.zip ]]; then
+              echo "Download error"
+            elif unzip -o byond.zip; then
+              break
+            else
+              ((attempt++))
+              ((minor++))
+              echo "BYOND_MINOR=$minor" >> $GITHUB_ENV
+              if (( attempt > max_attempts )); then
+                exit 1
+              fi
+            fi
+          done
           rm byond.zip
+          echo "Success unzip"
       - name: Install BYOND
         run: |
           echo "Install BYOND"
